In [1]:
import numpy as np, pandas as pd
import warnings
warnings.filterwarnings('ignore')

data = pd.read_excel('C:/Users/Gopi.Battineni/OneDrive - University of Limerick/Desktop/FORGE/Synthetic-data_Audit/Sample/Sample.xlsx')
data.replace({'diagnosis': {'M':1, 'B':0}}, inplace=True)
data.drop(['diagnosis'], axis=1, inplace= True)
data.head(11)

   radius_mean  radius_se  radius_worst
0        17.99     1.0950         25.38
1        20.57     0.5435         24.99
2        19.69     0.7456         23.57
3        11.42     0.4956         14.91
4        20.29     0.7572         22.54
5        12.45     0.3345         15.47
6        18.25     0.4467         22.88
7        13.71     0.5835         17.06
8        13.00     0.3063         15.49
9        12.46     0.2976         15.09

In [2]:
import sdv
from sdv.metadata import SingleTableMetadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data)

print(f"Data shape: {data.shape}")
print(f"Columns: {list(data.columns)}")

Data shape: (10, 3)
Columns: ['radius_mean', 'radius_se', 'radius_worst']

In [3]:
from sdv.single_table import CTGANSynthesizer, CopulaGANSynthesizer, GaussianCopulaSynthesizer, TVAESynthesizer
from sdv.evaluation.single_table import evaluate_quality, run_diagnostic

models = { 

    'CTGAN' : CTGANSynthesizer,
    'CopulaGAN': CopulaGANSynthesizer,
    'TVAE': TVAESynthesizer, 
    'GaussianCopula': GaussianCopulaSynthesizer
}

synthetic_data = {}
diagnostics = {}
quality_report = {}

for name, Synthesizer in models.items():
    print(f"\nSynthetsizing with {name}.......")

    model = Synthesizer(metadata)
    model.fit(data)

    synthetic_data[name] = model.sample(10)
    diagnostics[name] = run_diagnostic(data, synthetic_data[name], metadata)
    quality_report[name] = evaluate_quality(data, synthetic_data[name], metadata)
    
    print(f'{name} synthetic data generated successfully')

for name in models:
    print(f"Quality report for {name}:")
    print(quality_report[name])
    print("-" * 40)

from IPython.display import display

print("=========================================")

print("Synthetic data samples:")
for name in models:
    print(f"\nSynthetic data from {name}:")
    display(synthetic_data[name]) 
    print("-" * 40)

Synthetsizing with CTGAN.......
Generating report ...

(1/2) Evaluating Data Validity: |██████████| 3/3 [00:00<00:00, 191.02it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<?, ?it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 3/3 [00:00<00:00, 1556.91it/s]|
Column Shapes Score: 53.33%

(2/2) Evaluating Column Pair Trends: |██████████| 3/3 [00:00<00:00, 170.10it/s]|
Column Pair Trends Score: 51.73%

Overall Score (Average): 52.53%

CTGAN synthetic data generated successfully

Synthetsizing with CopulaGAN.......
Generating report ...

(1/2) Evaluating Data Validity: |██████████| 3/3 [00:00<?, ?it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<?, ?it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 3/3 [00:00<00:00, 1222.47it/s]|
Column Shapes Score: 63.33%

(2/2) Evaluating Column Pair Trends: |██████████| 3/3 [00:00<00:00, 152.82it/s]|
Column Pair Trends Score: 72.58%

Overall Score (Average): 67.96%

CopulaGAN synthetic data generated successfully

Synthetsizing with TVAE.......
Generating report ...

(1/2) Evaluating Data Validity: |██████████| 3/3 [00:00<?, ?it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<?, ?it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 3/3 [00:00<00:00, 2284.89it/s]|
Column Shapes Score: 66.67%

(2/2) Evaluating Column Pair Trends: |██████████| 3/3 [00:00<00:00, 171.55it/s]|
Column Pair Trends Score: 69.16%

Overall Score (Average): 67.91%

TVAE synthetic data generated successfully

Synthetsizing with GaussianCopula.......
Generating report ...

(1/2) Evaluating Data Validity: |██████████| 3/3 [00:00<?, ?it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<00:00, 60.79it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 3/3 [00:00<00:00, 2125.49it/s]|
Column Shapes Score: 66.67%

(2/2) Evaluating Column Pair Trends: |██████████| 3/3 [00:00<00:00, 167.83it/s]|
Column Pair Trends Score: 82.43%

Overall Score (Average): 74.55%

GaussianCopula synthetic data generated successfully
Quality report for CTGAN:
<sdmetrics.reports.single_table.quality_report.QualityReport object at 0x0000027C24D513C0>
----------------------------------------
Quality report for CopulaGAN:
<sdmetrics.reports.single_table.quality_report.QualityReport object at 0x0000027C24D51120>
----------------------------------------
Quality report for TVAE:
<sdmetrics.reports.single_table.quality_report.QualityReport object at 0x0000027C24D20A90>
----------------------------------------
Quality report for GaussianCopula:
<sdmetrics.reports.single_table.quality_report.QualityReport object at 0x0000027C24D50970>
----------------------------------------
=========================================
Synthetic data samples:

Synthetic data from CTGAN:

   radius_mean  radius_se  radius_worst
0        14.13     0.7885         18.30
1        19.69     0.5928         19.79
2        17.67     0.5874         22.88
3        17.86     0.9027         18.46
4        14.67     0.7439         14.95
5        16.78     0.6372         18.59
6        12.06     0.8939         20.33
7        17.56     0.7114         20.23
8        20.22     0.7543         20.01
9        19.57     0.2976         21.57

----------------------------------------

Synthetic data from CopulaGAN:

   radius_mean  radius_se  radius_worst
0        16.88     0.2980         25.31
1        17.43     1.0680         25.38
2        13.88     1.0950         25.38
3        20.57     0.2990         14.94
4        17.32     0.8391         14.91
5        15.98     0.3071         14.91
6        18.19     1.0522         25.38
7        18.23     0.2982         14.91
8        11.42     0.2976         16.21
9        18.43     1.0187         21.36

----------------------------------------

Synthetic data from TVAE:

   radius_mean  radius_se  radius_worst
0        13.46     0.4609         19.62
1        17.34     0.8578         18.41
2        15.73     0.5118         25.38
3        15.57     0.5981         21.54
4        16.29     0.7047         15.96
5        13.75     0.4673         15.62
6        13.90     0.3114         19.86
7        16.43     0.5492         20.79
8        18.07     0.5598         19.01
9        16.86     0.3601         16.89

----------------------------------------

Synthetic data from GaussianCopula:

   radius_mean  radius_se  radius_worst
0        20.26     0.4991         25.38
1        14.85     0.6578         16.07
2        15.05     0.4336         23.77
3        12.15     0.5404         21.79
4        17.92     0.7151         25.36
5        15.57     0.5245         14.99
6        16.27     0.6645         20.72
7        16.46     0.3369         25.38
8        20.57     0.9748         25.38
9        15.09     0.3762         14.92

----------------------------------------

In [5]:

import sdv
from sdv.metadata import SingleTableMetadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data)
print(f"Data shape: {data.shape}")
print(f"Columns: {list(data.columns)}")

Data shape: (10, 3)
Columns: ['radius_mean', 'radius_se', 'radius_worst']

In [8]:
synthetic_data_gaussian_copula = model.sample(10)

In [9]:
synthetic_data_gaussian_copula

   radius_mean  radius_se  radius_worst
0        14.83     0.3115         25.38
1        20.57     0.5304         25.38
2        14.06     0.4776         15.31
3        16.51     0.3327         24.72
4        11.42     0.3417         15.67
5        20.40     1.0320         19.91
6        19.69     0.3973         24.61
7        14.91     0.5368         14.91
8        11.42     0.3193         14.91
9        20.02     0.7778         24.18

In [10]:
data

   radius_mean  radius_se  radius_worst
0        17.99     1.0950         25.38
1        20.57     0.5435         24.99
2        19.69     0.7456         23.57
3        11.42     0.4956         14.91
4        20.29     0.7572         22.54
5        12.45     0.3345         15.47
6        18.25     0.4467         22.88
7        13.71     0.5835         17.06
8        13.00     0.3063         15.49
9        12.46     0.2976         15.09

In [11]:
from numpy.linalg import norm

real_data = data
synthetic_data = synthetic_data_gaussian_copula

# function to create similarity matrix

def normalize_rows(X):
  return X/(norm(X, axis=1, keepdims=True)+1e-12)

R = normalize_rows(real_data.to_numpy(float))
S = normalize_rows(synthetic_data.to_numpy(float))

cosine_matrix = R @ S.T